{% set name = "skopeo" %}
{% set version = "0.1.35" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/containers/skopeo/archive/v{{version}}.tar.gz
  sha256: 0d7024c09d7b1822acb174912f5b06950a023ef5d05d6b8b442e563c512b4c4a

build:
  number: 0
  skip: True  # [win]

requirements:
  build:
    - {{ compiler('cgo') }}
    - {{ compiler('c') }}

test:
  commands:
    - skopeo --help

about:
  home: https://github.com/containers/skopeo
  license: Apache-2.0
  license_family: Apache
  license_file: LICENSE
  summary: Perform operations on container images without docker daemon.
  description: |
    Skopeo can copy, inspect delete, sign and verify container images
    without requiring access to a docker daemon. It supports the local
    image store, API v2 registries, image archive (as created by
    docker save), OCI and OSTree and a local directory format.

extra:
  recipe-maintainers:
    - epruesse
    - bgruening
