travis:
  secure:
    BINSTAR_TOKEN: Kcekw2d0b4sOUE7I07JDaYw+RUdA8GestyHIuYA/xFkV+wuWLOZOaAonyePG6HkwNiBHEicRAlz+mYCmN50kgzs0puFQ4yZMqVg4m5SUTeqFCs/PAOBtvcH/UJBN8v+209sTT9oDaBtkg9/tBxWBkK9fbophXRKPzhSW/hqw1fn5V6UHddKBEpg2origsvjt5bNrKAeIZDmO7legQGIKL31tGMNh+5zFHGTylauu0KCfptl069abBllEcz0M9IoFlHzDSnKvZ/v5B98kh+IRO9KO/TZZN/QR9Q3IK76cJGFeCjlrcM0AO6bFzatp/P0t6NVxlt8eXNEWp1y6fuhikUCmy9c3A0RIbBAGis3njruAankpUy26GyyD4KBrguHo9gRYnHvALj0Wr0Mw45TkPXatEIouFzSwnPPahhFANOgPFoRanx02qN9lLvL0IPuOlaGvNNNewGpgRdNS5MmLbP/SlsY9TceMKRhKEifHOQYb6eRokJQyuV4UeeVEcF8kGgXsr5lTNK6wlpBWY8nWgVr+58HflhAe0npRucK+uWJGqOKetjZwJNkP3mAVs5xYY+8dRq1itoV59ugy0+NDpwVJJSrKFTU68qF1bmS5wCaCa0Ez53W3tPsPknSZH23QC3+mYxo7GxVKiOk/4ViI3lqCihn3PNNPKpE1sgTWJDY=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
conda_forge_output_validation: true
